### ISSUE TITLE
Data workflow e AcessPoint roadmap

### ISSUE THREAD

**Issue by EltonCN** [BReATH-Brazilian-Research/projeto-final-MC536#1]
Implementação mínima para iniciar o trabalho de MC886

- [x] Terminar de implementar o DB com o Neo4j
- [x] Alterar arquitetura: juntar Workflow com Requester
- [x] [DOING] Implementar componentes para requerir os dados de saúde básicos
- [ ] Implementar componentes para requerir os dados climáticos básicos
- [ ] Implementar as operações necessárias no AcessPoint para inserir os novos dados
- [ ] Criar operações no AcessPoint para requerir os dados necessários para o treino
- [ ] Criar operação para exportar os dados via CSV?
